apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - frontend/frontend-deployment.yaml
  - frontend/frontend-service.yaml
  - frontend/frontend-secret.yaml
  - backend/backend-deployment.yaml
  - backend/backend-service.yaml
  - backend/backend-secret.yaml
  - backend/backend-hpa.yaml
  - backend/backend-public-pvc.yaml
  - postgres/postgres-deployment.yaml
  - postgres/postgres-service.yaml
  - postgres/postgres-secret.yaml
  - postgres/postgres-pvc.yaml
  - postgres/postgres-init-configmap.yaml
  - https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml

patches:
  - target:
      kind: Deployment
      name: metrics-server
      namespace: kube-system
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --kubelet-insecure-tls
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --kubelet-preferred-address-types=InternalIP
