apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-server-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: backend
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      path: /metrics
      interval: 10s
