apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter-service
  labels:
    app: postgres-exporter
    release: prometheus
spec:
  type: NodePort
  ports:
    - name: http
      port: 9187
      targetPort: 9187
      nodePort: 30007
  selector:
    app: postgres-exporter